"""
Django settings for articleManager project.

Generated by 'django-admin startproject' using Django 1.8.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import os.path   
import sae.const 
BASE_DIR = os.path.dirname(os.path.dirname(__file__))

SECRET_KEY = 'x#=f0o4n$)b!zks=39t0y2p!%u1+op3907hmj*+hnj#hu1h+oe'
'''
MEDIA_URL = '/madia/'
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760
DEFAULT_FILE_STORAGE = 'sae.ext.django.storage.backend.Storage'
STORAGE_BUCKET_NAME = 'madia'

'''
MYSQL_DB = sae.const.MYSQL_DB   
MYSQL_USER = sae.const.MYSQL_USER   
MYSQL_PASS = sae.const.MYSQL_PASS   
MYSQL_HOST_M = sae.const.MYSQL_HOST   
MYSQL_HOST_S = sae.const.MYSQL_HOST_S   
MYSQL_PORT = sae.const.MYSQL_PORT  

TEMPLATE_DEBUG = False

DEBUG = True

DEFAULT_CHARSET='utf-8' 

ALLOWED_HOSTS=[
        '.sinaapp.com',
            ]


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'loginORreg',
    'accounts',
    'accounts.models',
    'pagination',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    #'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'pagination.middleware.PaginationMiddleware',
    
)


SAE_DEFAULT_STORAGE_DOMAIN_NAME = 'madia'
FILE_UPLOAD_MAX_MEMORY_SIZE = 20971520 
FILE_UPLOAD_TEMP_DIR = '/s/madia/tmp/' 


ROOT_URLCONF = 'articleManager.urls'
AUTH_PROFILE_MODULE = 'account.account'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'articleManager.wsgi.application'

# -*- coding: utf-8 -*-
# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {  
    'default': {  
        'ENGINE': 'django.db.backends.mysql',   
        'NAME': 'app_articlemanager',   
        'USER': MYSQL_USER,   
        'PASSWORD': MYSQL_PASS,   
        'HOST': MYSQL_HOST_M,   
        'PORT': MYSQL_PORT,   
    }  
}  
'''
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}
'''
EMAIL_HOST='smtp.yeah.net'
EMAIL_PORT=25
EMAIL_HOST_USER='ariticle_manager@yeah.net' 
EMAIL_HOST_PASSOWORD='icebreaker' 
EMAIL_SUBJECT_PREFIX = '[aricle_manager]'            
EMAIL_USE_TLS=True
SERVER_EMAIL = '13100962837@163.com'
# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(os.path.dirname(__file__),'static')
